{% set version = "1.3-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pwr
  version: {{ version|replace("-", "_") }}

source:
  fn: pwr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pwr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pwr/pwr_{{ version }}.tar.gz
  sha256: 5bb00747aa599b11f133e94c6e4999e592456e966cba3607bbd1fcb1c7f1dfcd

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('pwr')"           # [not win]
    - "\"%R%\" -e \"library('pwr')\""  # [win]

about:
  home: https://github.com/heliosdrm/pwr
  license: GPL (>= 3)
  summary: Power analysis functions along the lines of Cohen (1988).
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
