{% set version = '1.3-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pwr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pwr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pwr/pwr_{{ version }}.tar.gz
  sha256: 5bb00747aa599b11f133e94c6e4999e592456e966cba3607bbd1fcb1c7f1dfcd

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('pwr')"           # [not win]
    - "\"%R%\" -e \"library('pwr')\""  # [win]

about:
  home: https://github.com/heliosdrm/pwr
  license: GPL-3.0-or-later
  summary: Power analysis functions along the lines of Cohen (1988).
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pwr
# Version: 1.3-0
# Date: 2020-03-16
# Title: Basic Functions for Power Analysis
# Authors@R: c(person("Stephane", "Champely", role=c("aut")), person("Claus", "Ekstrom", role="ctb"), person("Peter", "Dalgaard", role="ctb"), person("Jeffrey", "Gill", role="ctb"), person("Stephan", "Weibelzahl", role="ctb"), person("Aditya", "Anandkumar", role="ctb"), person("Clay", "Ford", role="ctb"), person("Robert", "Volcic", role="ctb"), person("Helios", "De Rosario", role="cre", email="helios.derosario@gmail.com"))
# Description: Power analysis functions along the lines of Cohen (1988).
# Imports: stats, graphics
# Suggests: ggplot2, scales, knitr, rmarkdown
# License: GPL (>= 3)
# URL: https://github.com/heliosdrm/pwr
# VignetteBuilder: knitr
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2020-03-16 22:50:22 UTC; meliana
# Author: Stephane Champely [aut], Claus Ekstrom [ctb], Peter Dalgaard [ctb], Jeffrey Gill [ctb], Stephan Weibelzahl [ctb], Aditya Anandkumar [ctb], Clay Ford [ctb], Robert Volcic [ctb], Helios De Rosario [cre]
# Maintainer: Helios De Rosario <helios.derosario@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-03-17 12:10:02 UTC
