travis:
  secure:
    BINSTAR_TOKEN: TMohLfawcgsv/I9gzPEVFLHVTIDD81nk0Go5DIeoYssCc46Adkj1YvEmPMP2/wuniCmJstOkxG+KEVzbhDL2b7r0886bu6WQOw/ZF4Z/iAlytnoxRozkj6uTtHruK0V0n0FEYGd7aWkunJM7New76XvEm9fir5YY+3LGb3mwIhQI2UcGBcSGBtTIBUPtgtyofnK1CuBAvgkUBR3vi0Pb4X5L8hHkM3+0VDpz4qeMA2f7qquRsDjmKHJN3jdPh90sAwWabSeIQDfnrHfPw4R443BCQVVNiUsQ5YoiwJ5ido6RxcBP5nFnFaSJKyDYyvs2Yp2MWJj3Zvz9Rr6DRCLzX3e7rMEgslWu5Iso434lkaXsphzWfWFtJFYBa1W1upeNuQ3cwpduxZbpekkn+dei+QaSE9O6HJzwwVhQIcw+ixN72ovZpqv1jy9UZAkaZEelgaIwKfhYKIOvxZvMqkBT7fh41VaUv9EHkoTdcOB2UcYqyLpzDFgw6/9WDVSWPrFIhhfTuehcbgLpNdbmxevD6sSNzidkQfDBc0jVIoLvcesrR6aV9fCQv1mpEz3hpDXnuEdhwD/lNGkZMte9bfYfLuUu/c2CzVz/4OMyzlYH3Rq1YmkIHlpOvrs/tykCIEI4FiChJZCRUF2d4huQZYquSgWhhYy0U56KRKseIGiqKQU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
