travis:
  secure:
    BINSTAR_TOKEN: Jk9Cbzrhpgc9BIOHFAN7gvZiupOB3L4ycd/PzlqZ6n4uDz7Si8LnRZrDWPxSNuWJGkiihvtYyv6mr3AK9g01F8cO3qusgVdhAojjV/aM4IYn95uaSv8VoHSE6lN4i2Ddc+06dktoKqvEl0Gl3JnqmxiaalHuiHCO4uuVvHXTk7h3yZ74YQFTDN5+Qe6kMiS5h7bzIfHpgPBHonYUBqbgf0NS5hHSbxrqPtLJR3RRG9gZw7KbYcpsjyg/Wp1oVOi/xlFo1mU5sRcjxB982q3nI/TmF+ZoX+bsUArQq99qfOuS6sRl9lZBFwpO6vnRpVKZ7qU7uIGGes2oDEH2gXb8u+Cz/thHZufs3is0DK1CX2lRTw8Z/dqTyufJAXb4ER6Wo9OWNKBBzC0hhVFguM+fAlHbIA8VB8UmIugpzae2khyYMQKoAWprwwPFVTpo9Ak/2w6PuA/rGvKkhOoe+WFinjFAdSoQUpYaQYDgTdJFp+8sjsQJ52N5xehYNz4C/p3rSagdfjsdsTVcxc7hvW0DJdS5ANDpHJjhunlAGULaUAEhMSC9OW3IUYRFN2F6S8hUROazbbbo157zJKtftf1oGkeVe6GnxLMk4HvCrP98n2q2gNxJ4ZL+i2zEEIB0NeukH+w8WUW2MAholVZBeDLgBfuS/JOmRZ1Lxg40Z+jagKY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
