travis:
  secure:
    BINSTAR_TOKEN: jICSYSe4BuXcpywZi1z2U8d3heCSLny/L7K/pK7oXw3u0l/fmnlEAO8btSnCPSHGQ853WcG2SiWXhZdlUCgmgSy189cHSwANsCUuDPWKsui2mQR3+FRvNVP0UpUmAGNGL3VACq5IyHwRjAj99J9JxY8Aq4CtA2gTdWF+jDKLsfTlaVUliHw1dUPu02UB2E2QPNunMwdc0DO9afUh0r35AxmyOYT4f9KzvaCHDdoqyP+5vC6SMakUVkBom33ngJFtOeGx3yO3WyjgOXbHOd+6WKtltaYO2fTHKZfRgUz5P5/Kci46XnDjNaduqiODZUEiG2ozJW/Y05Z3toRz01jvypCmbHQf5p2Lu21GaliF56m3kPc/nsofxIbZTBm7Jra/3G2FRB+dVgMcybbULxEqqLbRLy/Vi3PykF2cs2qa/G/qj6pz7fv/m+uCbC3beS4eWaYWeBXWaRTbxol5gA9++6tgjReLd4jr53HoIB6e3h4JlatTV11322xgyBM/817i2f1Rvz1a80yh7fIko3SdEjmUy2uhc+2n6igiB7br568OH3NEWIz1hgM0LYZu9Nr9AFH7rmFQkIezPsr6X+vlzxuOfJxZkp7U0hV2mztw73GcJlpLVemrHbsdXXxcnbrxXfUO4N2zQXGnMytJOXLvNAQ35iFhyjvGphquT+pwji0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
